### ISSUE TITLE
Evaluation of unsupervised embedding (trainMode 5)

### ISSUE THREAD

**Issue by bluebyte9001** [facebookresearch/StarSpace#107]
Which possibilities exist (out of the box) for evaluating/testing the unsupervised model (unsupervised word embeddings, trainMode 5)? When I try to use the unsupervised model as input for test -testFile (supervised classification), I only receive error "Test is undefined in trainMode5. Please use other trainMode for testing".

It would have been nice if we could use supervised classification (trainMode 0) as surrogate for testing the performance of the unsupervised learner (trainMode 5). That is, provide the trainMode 5 model (representation of the input) as input for a supervised classifier performing some task related to the domain the data is from. 

Is this somehow possible, or something you plan to implement? It would then be possible to measure the performance of StarSpace (and the potential improvements it brings) more directly against other supervised classifiers using standard performance metrics.

**Comment by jaseweston** [comment]
You can certainly do this (semisupervised learning) with something like SentEval, which is what we did in the paper:
https://arxiv.org/abs/1709.03856
(See Tables 9 & 10). That trains a classifier on top of the embeddings.
Switching to trainMode 0 does something different, it tries to retrain the embeddings for a supervised task (rather than train something on top) -- and if there aren't enough training examples we're not sure that will work well...

**Comment by jaseweston** [comment]
In addition to my other comments, note you can now also multitask the two tasks, see: 
https://github.com/facebookresearch/StarSpace/commit/57c6212e89be5789487fbb96e860f5193ecad7fc
Closing this issue.
