### ISSUE TITLE
How to use bag of words with arbitrary ngrams? i.e. all neighbours are considered

### ISSUE THREAD

**Issue by ljmartin** [facebookresearch/StarSpace#241]
Hi,
Thanks for StarSpace!

~~How can one~~ Is it possible to use the `__label__protein drugA drugB` format without taking nearest neighbours for the words? I'd like to try embedding both proteins (the labels) and drug names (the words) together, but the drug names have no defined order, like a sentence would, so ngrams don't make sense. Ideally I could consider ALL word neighbours. My dataset has up to 3-4000 words per label.

I've tried setting `-ngram` to 0 or very large. 0 results in all vectors being almost exactly the same, large (1000) stalled my laptop :)

Thanks!

**Comment by ckingdev** [comment]
There are 5 * 10^201 combinations of 100 words from a vocabulary of 4000. Of course your laptop stalled! If you had just a single byte per ngram for the embedding, you'd need 5 * 10^177 yottabytes. StarSpace creates a vector for each ngram, so if you want to get explicit embeddings for sets of features you'll need to be careful with the number.

If you're instead looking for a way to train to predict the label(s) with all of the features, that's what ngrams = 1 and the default training mode do. I suspect that you are learning the average because there are so many features with not enough to discriminate between them.

**Comment by ljmartin** [comment]
Thanks @ckingdev ! I misunderstood ngrams=1 to mean 'take the centre word AND 1 adjacent neighbour'. 
cheers
